### ISSUE TITLE
Multiple pages simultaneously

### ISSUE THREAD

**Issue by thomasgroch** [rickydunlop/fbmessenger-node#41]
What would be the propper way to use fbmessenger with multiple pages simultaneously?

* Instantiate again the global fbmessenger variable.
* Work with an array of fbmessenger instances.

Thanks.

**Comment by rickydunlop** [comment]
Hey Thomas,
The main thing you need to do is change the pageAccessToken which you can do by creating a new instance or dynamically changing an instance using `messenger.pageAccessToken=<my token>`.

There's a couple of ways you could do this:

- Have one Messenger instance and switch the pageAccessToken based on [`recipient.id`](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/#format) 
This will be your page ID, so you could have a lookup object that you use to get the correct access token for that Page ID.
```js
const accessTokens = {
  pageId1: 'page1AccessToken',
  pageId2: 'page2AccessToken',
};

messenger.pageAccessToken = accessTokens[message.recipient.id];
```
- Have different endpoints on your server e.g `/bot1` for one instance, `bot2` for another etc

Try it out and let me know how it goes.

**Comment by rickydunlop** [comment]
Closing this as it's 2 years old now
